name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Debug APK

    steps:
      # --- Step 1: Checkout source ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Step 2: Set up Java (Gradle requires JDK) ---
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # --- Step 3: Cache Gradle dependencies for faster builds ---
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # --- Step 4: Make Gradle executable ---
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # --- Step 5: Build Debug APK ---
      - name: Build Debug
        run: ./gradlew clean assembleDebug --stacktrace

      # --- Step 6: Run static checks (optional but recommended) ---
      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # --- Step 7: Upload built APK as artifact ---
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: LiveNotificationsDemo-debug
          path: app/build/outputs/apk/debug/*.apk
